'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _getPrototypeOf = require('babel-runtime/core-js/object/get-prototype-of');

var _getPrototypeOf2 = _interopRequireDefault(_getPrototypeOf);

var _classCallCheck2 = require('babel-runtime/helpers/classCallCheck');

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

var _createClass2 = require('babel-runtime/helpers/createClass');

var _createClass3 = _interopRequireDefault(_createClass2);

var _possibleConstructorReturn2 = require('babel-runtime/helpers/possibleConstructorReturn');

var _possibleConstructorReturn3 = _interopRequireDefault(_possibleConstructorReturn2);

var _get2 = require('babel-runtime/helpers/get');

var _get3 = _interopRequireDefault(_get2);

var _inherits2 = require('babel-runtime/helpers/inherits');

var _inherits3 = _interopRequireDefault(_inherits2);

var _client = require('soundworks/client');

var soundworks = _interopRequireWildcard(_client);

var _SampleSynth = require('./SampleSynth');

var _SampleSynth2 = _interopRequireDefault(_SampleSynth);

var _Looper = require('./Looper');

var _Looper2 = _interopRequireDefault(_Looper);

var _Circles = require('./Circles');

var _Circles2 = _interopRequireDefault(_Circles);

var _audioFiles = require('./audioFiles');

var _audioFiles2 = _interopRequireDefault(_audioFiles);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var client = soundworks.client;

var viewTemplate = '\n  <canvas class="background"></canvas>\n  <div class="foreground">\n    <div class="section-top flex-middle"></div>\n    <div class="section-center flex-center">\n    <% if (state === \'reset\') { %>\n      <p>Waiting for<br>everybody<br>getting ready…</p>\n    <% } else if (state === \'end\') { %>\n      <p>That\'s all.<br>Thanks!</p>\n    <% } else { %>\n      <p>\n      <% if (numAvailable > 0) { %>\n        You have<br />\n        <% if (numAvailable === maxDrops) { %>\n          <span class="huge"><%= numAvailable %></span>\n        <% } else { %>\n          <span class="huge"><%= numAvailable %> of <%= maxDrops %></span>\n        <% } %>\n        <br /><%= (numAvailable === 1) ? \'drop\' : \'drops\' %> to play\n      <% } else { %>\n        <span class="big">Listen!</span>\n      <% } %>\n      </p>\n    <% } %>\n    </div>\n    <div class="section-bottom flex-middle"></div>\n  </div>\n';

var PlayerExperience = function (_soundworks$Experienc) {
  (0, _inherits3.default)(PlayerExperience, _soundworks$Experienc);

  function PlayerExperience() {
    (0, _classCallCheck3.default)(this, PlayerExperience);


    // configure required services

    var _this = (0, _possibleConstructorReturn3.default)(this, (0, _getPrototypeOf2.default)(PlayerExperience).call(this));

    _this.welcome = _this.require('welcome');
    _this.loader = _this.require('loader', { files: _audioFiles2.default });
    _this.checkin = _this.require('checkin');
    _this.sync = _this.require('sync');
    _this.params = _this.require('shared-params');
    _this.motionInput = _this.require('motion-input', { descriptors: ['accelerationIncludingGravity'] });
    _this.scheduler = _this.require('scheduler', { lookahead: 0.050 });

    // requires mobile device
    _this.require('platform', { features: 'mobile-device' });

    // a simple sample player with a list of samples
    _this.synth = new _SampleSynth2.default();

    // control parameters
    _this.state = 'reset';
    _this.maxDrops = 0;

    _this.loopParams = {};
    _this.loopParams.div = 3;
    _this.loopParams.period = 7.5;
    _this.loopParams.attenuation = 0.70710678118655;
    _this.loopParams.minGain = 0.1;

    _this.autoPlay = 'off'; // automatic (random) playing: 'disable', 'off', 'on'
    _this.quantize = 0; // quantization step in

    // renderer generating growing circles on touch
    _this.renderer = new _Circles2.default();

    // each touch starts its own loop generated by the 'looper'
    _this.looper = new _Looper2.default(_this.scheduler, _this.synth, _this.renderer, _this.loopParams, function () {
      return _this.updateCount();
    });
    return _this;
  }

  (0, _createClass3.default)(PlayerExperience, [{
    key: 'init',
    value: function init() {
      // setup view (creator, template and content)
      this.viewCtor = soundworks.CanvasView;
      this.viewTemplate = viewTemplate;
      this.viewContent = {
        state: this.state,
        maxDrop: 0,
        numAvailable: 0
      };

      // create view with the creator, template and content given above
      this.view = this.createView();
    }
  }, {
    key: 'trigger',
    value: function trigger(x, y) {
      var soundParams = {
        index: client.index,
        gain: 1,
        x: x,
        y: y
      };

      var time = this.scheduler.syncTime;

      // quantize
      // if (this.quantize > 0)
      //   serverTime = Math.ceil(time / this.quantize) * this.quantize;

      this.looper.start(time, soundParams, true);
      this.send('sound', time, soundParams);
    }
  }, {
    key: 'clear',
    value: function clear() {
      // remove at own looper
      this.looper.remove(client.index, true);

      // remove at other players
      this.send('clear');
    }
  }, {
    key: 'updateCount',
    value: function updateCount() {
      this.viewContent.maxDrops = this.maxDrops;
      this.viewContent.message = undefined;

      if (this.state === 'reset') {
        this.viewContent.state = 'reset';
      } else if (this.state === 'end' && this.looper.loops.length === 0) {
        this.viewContent.state = 'end';
      } else {
        this.viewContent.state = this.state;
        this.viewContent.numAvailable = Math.max(0, this.maxDrops - this.looper.numLocalLoops);
      }

      this.view.render('.section-center');
    }
  }, {
    key: 'autoTrigger',
    value: function autoTrigger() {
      var _this2 = this;

      if (this.autoPlay === 'on') {
        if (this.state === 'running' && this.looper.numLocalLoops < this.maxDrops) this.trigger(Math.random(), Math.random());

        setTimeout(function () {
          _this2.autoTrigger();
        }, Math.random() * 2000 + 50);
      }
    }
  }, {
    key: 'autoClear',
    value: function autoClear() {
      var _this3 = this;

      if (this.autoPlay === 'on') {
        if (this.looper.numLocalLoops > 0) this.clear(Math.random(), Math.random());

        setTimeout(function () {
          _this3.autoClear();
        }, Math.random() * 60000 + 60000);
      }
    }
  }, {
    key: 'setState',
    value: function setState(state) {
      if (state !== this.state) {
        this.state = state;
        this.updateCount();
      }
    }
  }, {
    key: 'setMaxDrops',
    value: function setMaxDrops(maxDrops) {
      if (maxDrops !== this.maxDrops) {
        this.maxDrops = maxDrops;
        this.updateCount();
      }
    }
  }, {
    key: 'setAutoPlay',
    value: function setAutoPlay(autoPlay) {
      if (this.autoPlay !== 'disable' && autoPlay !== this.autoPlay) {
        this.autoPlay = autoPlay;

        if (autoPlay === 'on') {
          this.autoTrigger();
          this.autoClear();
        }
      }
    }
  }, {
    key: 'start',
    value: function start() {
      var _this4 = this;

      (0, _get3.default)((0, _getPrototypeOf2.default)(PlayerExperience.prototype), 'start', this).call(this);

      // just init once
      if (!this.hasStarted) this.init();

      // show view
      this.show();

      // setup shared parameter (conductor) listeners
      var params = this.params;
      params.addItemListener('state', function (state) {
        return _this4.setState(state);
      });
      params.addItemListener('maxDrops', function (value) {
        return _this4.setMaxDrops(value);
      });
      params.addItemListener('loopDiv', function (value) {
        return _this4.loopParams.div = value;
      });
      params.addItemListener('loopPeriod', function (value) {
        return _this4.loopParams.period = value;
      });
      params.addItemListener('loopAttenuation', function (value) {
        return _this4.loopParams.attenuation = value;
      });
      params.addItemListener('minGain', function (value) {
        return _this4.loopParams.minGain = value;
      });
      params.addItemListener('autoPlay', function (value) {
        return _this4.setAutoPlay(value);
      });
      params.addItemListener('clear', function () {
        return _this4.looper.removeAll();
      });

      // setup motion input listeners
      if (this.motionInput.isAvailable('accelerationIncludingGravity')) {
        this.motionInput.addListener('accelerationIncludingGravity', function (data) {
          var accX = data[0];
          var accY = data[1];
          var accZ = data[2];
          var mag = Math.sqrt(accX * accX + accY * accY + accZ * accZ);

          // clear screen on shaking
          if (mag > 20) {
            _this4.clear();
            _this4.autoPlay = 'disable'; // disable auto play on shake
          }
        });
      }

      // create touch event source referring to our view
      var surface = new soundworks.TouchSurface(this.view.$el);

      // setup touch listeners
      surface.addListener('touchstart', function (id, normX, normY) {
        if (_this4.state === 'running' && _this4.looper.numLocalLoops < _this4.maxDrops) _this4.trigger(normX, normY);

        _this4.autoPlay = 'disable'; // disable auto play on touch
      });

      // setup listeners for messages from server
      this.receive('echo', function (time, soundParams) {
        return _this4.looper.start(time, soundParams);
      });
      this.receive('clear', function (index) {
        return _this4.looper.remove(index);
      });

      // rederer starts with black screen
      this.view.setPreRender(function (ctx) {
        ctx.fillStyle = '#000';
        ctx.fillRect(0, 0, ctx.width, ctx.height);
      });

      // add renderer to view
      this.view.addRenderer(this.renderer);

      // set synth audio buffers
      this.synth.audioBuffers = this.loader.buffers;

      // launch autoplay (for testing)
      if (this.autoPlay) {
        this.autoTrigger();
        this.autoClear();
      }
    }
  }]);
  return PlayerExperience;
}(soundworks.Experience);

exports.default = PlayerExperience;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIlBsYXllckV4cGVyaWVuY2UuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBQUE7O0lBQVk7O0FBQ1o7Ozs7QUFDQTs7OztBQUNBOzs7O0FBQ0E7Ozs7Ozs7O0FBRUEsSUFBTSxTQUFTLFdBQVcsTUFBWDs7QUFFZixJQUFNLDQ1QkFBTjs7SUE2QnFCOzs7QUFDbkIsV0FEbUIsZ0JBQ25CLEdBQWM7d0NBREssa0JBQ0w7Ozs7OzZGQURLLDhCQUNMOztBQUlaLFVBQUssT0FBTCxHQUFlLE1BQUssT0FBTCxDQUFhLFNBQWIsQ0FBZixDQUpZO0FBS1osVUFBSyxNQUFMLEdBQWMsTUFBSyxPQUFMLENBQWEsUUFBYixFQUF1QixFQUFFLDJCQUFGLEVBQXZCLENBQWQsQ0FMWTtBQU1aLFVBQUssT0FBTCxHQUFlLE1BQUssT0FBTCxDQUFhLFNBQWIsQ0FBZixDQU5ZO0FBT1osVUFBSyxJQUFMLEdBQVksTUFBSyxPQUFMLENBQWEsTUFBYixDQUFaLENBUFk7QUFRWixVQUFLLE1BQUwsR0FBYyxNQUFLLE9BQUwsQ0FBYSxlQUFiLENBQWQsQ0FSWTtBQVNaLFVBQUssV0FBTCxHQUFtQixNQUFLLE9BQUwsQ0FBYSxjQUFiLEVBQTZCLEVBQUUsYUFBYSxDQUFDLDhCQUFELENBQWIsRUFBL0IsQ0FBbkIsQ0FUWTtBQVVaLFVBQUssU0FBTCxHQUFpQixNQUFLLE9BQUwsQ0FBYSxXQUFiLEVBQTBCLEVBQUUsV0FBVyxLQUFYLEVBQTVCLENBQWpCOzs7QUFWWSxTQWFaLENBQUssT0FBTCxDQUFhLFVBQWIsRUFBeUIsRUFBRSxVQUFVLGVBQVYsRUFBM0I7OztBQWJZLFNBZ0JaLENBQUssS0FBTCxHQUFhLDJCQUFiOzs7QUFoQlksU0FtQlosQ0FBSyxLQUFMLEdBQWEsT0FBYixDQW5CWTtBQW9CWixVQUFLLFFBQUwsR0FBZ0IsQ0FBaEIsQ0FwQlk7O0FBc0JaLFVBQUssVUFBTCxHQUFrQixFQUFsQixDQXRCWTtBQXVCWixVQUFLLFVBQUwsQ0FBZ0IsR0FBaEIsR0FBc0IsQ0FBdEIsQ0F2Qlk7QUF3QlosVUFBSyxVQUFMLENBQWdCLE1BQWhCLEdBQXlCLEdBQXpCLENBeEJZO0FBeUJaLFVBQUssVUFBTCxDQUFnQixXQUFoQixHQUE4QixnQkFBOUIsQ0F6Qlk7QUEwQlosVUFBSyxVQUFMLENBQWdCLE9BQWhCLEdBQTBCLEdBQTFCLENBMUJZOztBQTRCWixVQUFLLFFBQUwsR0FBZ0IsS0FBaEI7QUE1QlksU0E2QlosQ0FBSyxRQUFMLEdBQWdCLENBQWhCOzs7QUE3QlksU0FnQ1osQ0FBSyxRQUFMLEdBQWdCLHVCQUFoQjs7O0FBaENZLFNBbUNaLENBQUssTUFBTCxHQUFjLHFCQUFXLE1BQUssU0FBTCxFQUFnQixNQUFLLEtBQUwsRUFBWSxNQUFLLFFBQUwsRUFBZSxNQUFLLFVBQUwsRUFBaUI7YUFBTSxNQUFLLFdBQUw7S0FBTixDQUFyRixDQW5DWTs7R0FBZDs7NkJBRG1COzsyQkF1Q1o7O0FBRUwsV0FBSyxRQUFMLEdBQWdCLFdBQVcsVUFBWCxDQUZYO0FBR0wsV0FBSyxZQUFMLEdBQW9CLFlBQXBCLENBSEs7QUFJTCxXQUFLLFdBQUwsR0FBbUI7QUFDakIsZUFBTyxLQUFLLEtBQUw7QUFDUCxpQkFBUyxDQUFUO0FBQ0Esc0JBQWMsQ0FBZDtPQUhGOzs7QUFKSyxVQVdMLENBQUssSUFBTCxHQUFZLEtBQUssVUFBTCxFQUFaLENBWEs7Ozs7NEJBY0MsR0FBRyxHQUFHO0FBQ1osVUFBTSxjQUFjO0FBQ2xCLGVBQU8sT0FBTyxLQUFQO0FBQ1AsY0FBTSxDQUFOO0FBQ0EsV0FBRyxDQUFIO0FBQ0EsV0FBRyxDQUFIO09BSkksQ0FETTs7QUFRWixVQUFJLE9BQU8sS0FBSyxTQUFMLENBQWUsUUFBZjs7Ozs7O0FBUkMsVUFjWixDQUFLLE1BQUwsQ0FBWSxLQUFaLENBQWtCLElBQWxCLEVBQXdCLFdBQXhCLEVBQXFDLElBQXJDLEVBZFk7QUFlWixXQUFLLElBQUwsQ0FBVSxPQUFWLEVBQW1CLElBQW5CLEVBQXlCLFdBQXpCLEVBZlk7Ozs7NEJBa0JOOztBQUVOLFdBQUssTUFBTCxDQUFZLE1BQVosQ0FBbUIsT0FBTyxLQUFQLEVBQWMsSUFBakM7OztBQUZNLFVBS04sQ0FBSyxJQUFMLENBQVUsT0FBVixFQUxNOzs7O2tDQVFNO0FBQ1osV0FBSyxXQUFMLENBQWlCLFFBQWpCLEdBQTRCLEtBQUssUUFBTCxDQURoQjtBQUVaLFdBQUssV0FBTCxDQUFpQixPQUFqQixHQUEyQixTQUEzQixDQUZZOztBQUlaLFVBQUksS0FBSyxLQUFMLEtBQWUsT0FBZixFQUF3QjtBQUMxQixhQUFLLFdBQUwsQ0FBaUIsS0FBakIsR0FBeUIsT0FBekIsQ0FEMEI7T0FBNUIsTUFFTyxJQUFJLEtBQUssS0FBTCxLQUFlLEtBQWYsSUFBd0IsS0FBSyxNQUFMLENBQVksS0FBWixDQUFrQixNQUFsQixLQUE2QixDQUE3QixFQUFnQztBQUNqRSxhQUFLLFdBQUwsQ0FBaUIsS0FBakIsR0FBeUIsS0FBekIsQ0FEaUU7T0FBNUQsTUFFQTtBQUNMLGFBQUssV0FBTCxDQUFpQixLQUFqQixHQUF5QixLQUFLLEtBQUwsQ0FEcEI7QUFFTCxhQUFLLFdBQUwsQ0FBaUIsWUFBakIsR0FBZ0MsS0FBSyxHQUFMLENBQVMsQ0FBVCxFQUFZLEtBQUssUUFBTCxHQUFnQixLQUFLLE1BQUwsQ0FBWSxhQUFaLENBQTVELENBRks7T0FGQTs7QUFPUCxXQUFLLElBQUwsQ0FBVSxNQUFWLENBQWlCLGlCQUFqQixFQWJZOzs7O2tDQWdCQTs7O0FBQ1osVUFBSSxLQUFLLFFBQUwsS0FBa0IsSUFBbEIsRUFBd0I7QUFDMUIsWUFBSSxLQUFLLEtBQUwsS0FBZSxTQUFmLElBQTRCLEtBQUssTUFBTCxDQUFZLGFBQVosR0FBNEIsS0FBSyxRQUFMLEVBQzFELEtBQUssT0FBTCxDQUFhLEtBQUssTUFBTCxFQUFiLEVBQTRCLEtBQUssTUFBTCxFQUE1QixFQURGOztBQUdBLG1CQUFXLFlBQU07QUFDZixpQkFBSyxXQUFMLEdBRGU7U0FBTixFQUVSLEtBQUssTUFBTCxLQUFnQixJQUFoQixHQUF1QixFQUF2QixDQUZILENBSjBCO09BQTVCOzs7O2dDQVVVOzs7QUFDVixVQUFJLEtBQUssUUFBTCxLQUFrQixJQUFsQixFQUF3QjtBQUMxQixZQUFJLEtBQUssTUFBTCxDQUFZLGFBQVosR0FBNEIsQ0FBNUIsRUFDRixLQUFLLEtBQUwsQ0FBVyxLQUFLLE1BQUwsRUFBWCxFQUEwQixLQUFLLE1BQUwsRUFBMUIsRUFERjs7QUFHQSxtQkFBVyxZQUFNO0FBQ2YsaUJBQUssU0FBTCxHQURlO1NBQU4sRUFFUixLQUFLLE1BQUwsS0FBZ0IsS0FBaEIsR0FBd0IsS0FBeEIsQ0FGSCxDQUowQjtPQUE1Qjs7Ozs2QkFVTyxPQUFPO0FBQ2QsVUFBSSxVQUFVLEtBQUssS0FBTCxFQUFZO0FBQ3hCLGFBQUssS0FBTCxHQUFhLEtBQWIsQ0FEd0I7QUFFeEIsYUFBSyxXQUFMLEdBRndCO09BQTFCOzs7O2dDQU1VLFVBQVU7QUFDcEIsVUFBSSxhQUFhLEtBQUssUUFBTCxFQUFlO0FBQzlCLGFBQUssUUFBTCxHQUFnQixRQUFoQixDQUQ4QjtBQUU5QixhQUFLLFdBQUwsR0FGOEI7T0FBaEM7Ozs7Z0NBTVUsVUFBVTtBQUNwQixVQUFJLEtBQUssUUFBTCxLQUFrQixTQUFsQixJQUErQixhQUFhLEtBQUssUUFBTCxFQUFlO0FBQzdELGFBQUssUUFBTCxHQUFnQixRQUFoQixDQUQ2RDs7QUFHN0QsWUFBSSxhQUFhLElBQWIsRUFBbUI7QUFDckIsZUFBSyxXQUFMLEdBRHFCO0FBRXJCLGVBQUssU0FBTCxHQUZxQjtTQUF2QjtPQUhGOzs7OzRCQVVNOzs7QUFDTix1REEvSWlCLHNEQStJakI7OztBQURNLFVBSUYsQ0FBQyxLQUFLLFVBQUwsRUFDSCxLQUFLLElBQUwsR0FERjs7O0FBSk0sVUFRTixDQUFLLElBQUw7OztBQVJNLFVBV0EsU0FBUyxLQUFLLE1BQUwsQ0FYVDtBQVlOLGFBQU8sZUFBUCxDQUF1QixPQUF2QixFQUFnQyxVQUFDLEtBQUQ7ZUFBVyxPQUFLLFFBQUwsQ0FBYyxLQUFkO09BQVgsQ0FBaEMsQ0FaTTtBQWFOLGFBQU8sZUFBUCxDQUF1QixVQUF2QixFQUFtQyxVQUFDLEtBQUQ7ZUFBVyxPQUFLLFdBQUwsQ0FBaUIsS0FBakI7T0FBWCxDQUFuQyxDQWJNO0FBY04sYUFBTyxlQUFQLENBQXVCLFNBQXZCLEVBQWtDLFVBQUMsS0FBRDtlQUFXLE9BQUssVUFBTCxDQUFnQixHQUFoQixHQUFzQixLQUF0QjtPQUFYLENBQWxDLENBZE07QUFlTixhQUFPLGVBQVAsQ0FBdUIsWUFBdkIsRUFBcUMsVUFBQyxLQUFEO2VBQVcsT0FBSyxVQUFMLENBQWdCLE1BQWhCLEdBQXlCLEtBQXpCO09BQVgsQ0FBckMsQ0FmTTtBQWdCTixhQUFPLGVBQVAsQ0FBdUIsaUJBQXZCLEVBQTBDLFVBQUMsS0FBRDtlQUFXLE9BQUssVUFBTCxDQUFnQixXQUFoQixHQUE4QixLQUE5QjtPQUFYLENBQTFDLENBaEJNO0FBaUJOLGFBQU8sZUFBUCxDQUF1QixTQUF2QixFQUFrQyxVQUFDLEtBQUQ7ZUFBVyxPQUFLLFVBQUwsQ0FBZ0IsT0FBaEIsR0FBMEIsS0FBMUI7T0FBWCxDQUFsQyxDQWpCTTtBQWtCTixhQUFPLGVBQVAsQ0FBdUIsVUFBdkIsRUFBbUMsVUFBQyxLQUFEO2VBQVcsT0FBSyxXQUFMLENBQWlCLEtBQWpCO09BQVgsQ0FBbkMsQ0FsQk07QUFtQk4sYUFBTyxlQUFQLENBQXVCLE9BQXZCLEVBQWdDO2VBQU0sT0FBSyxNQUFMLENBQVksU0FBWjtPQUFOLENBQWhDOzs7QUFuQk0sVUFzQkYsS0FBSyxXQUFMLENBQWlCLFdBQWpCLENBQTZCLDhCQUE3QixDQUFKLEVBQWtFO0FBQ2hFLGFBQUssV0FBTCxDQUFpQixXQUFqQixDQUE2Qiw4QkFBN0IsRUFBNkQsVUFBQyxJQUFELEVBQVU7QUFDckUsY0FBTSxPQUFPLEtBQUssQ0FBTCxDQUFQLENBRCtEO0FBRXJFLGNBQU0sT0FBTyxLQUFLLENBQUwsQ0FBUCxDQUYrRDtBQUdyRSxjQUFNLE9BQU8sS0FBSyxDQUFMLENBQVAsQ0FIK0Q7QUFJckUsY0FBTSxNQUFNLEtBQUssSUFBTCxDQUFVLE9BQU8sSUFBUCxHQUFjLE9BQU8sSUFBUCxHQUFjLE9BQU8sSUFBUCxDQUE1Qzs7O0FBSitELGNBT2pFLE1BQU0sRUFBTixFQUFVO0FBQ1osbUJBQUssS0FBTCxHQURZO0FBRVosbUJBQUssUUFBTCxHQUFnQixTQUFoQjtBQUZZLFdBQWQ7U0FQMkQsQ0FBN0QsQ0FEZ0U7T0FBbEU7OztBQXRCTSxVQXNDQSxVQUFVLElBQUksV0FBVyxZQUFYLENBQXdCLEtBQUssSUFBTCxDQUFVLEdBQVYsQ0FBdEM7OztBQXRDQSxhQXlDTixDQUFRLFdBQVIsQ0FBb0IsWUFBcEIsRUFBa0MsVUFBQyxFQUFELEVBQUssS0FBTCxFQUFZLEtBQVosRUFBc0I7QUFDdEQsWUFBSSxPQUFLLEtBQUwsS0FBZSxTQUFmLElBQTRCLE9BQUssTUFBTCxDQUFZLGFBQVosR0FBNEIsT0FBSyxRQUFMLEVBQzFELE9BQUssT0FBTCxDQUFhLEtBQWIsRUFBb0IsS0FBcEIsRUFERjs7QUFHQSxlQUFLLFFBQUwsR0FBZ0IsU0FBaEI7QUFKc0QsT0FBdEIsQ0FBbEM7OztBQXpDTSxVQWlETixDQUFLLE9BQUwsQ0FBYSxNQUFiLEVBQXFCLFVBQUMsSUFBRCxFQUFPLFdBQVA7ZUFBdUIsT0FBSyxNQUFMLENBQVksS0FBWixDQUFrQixJQUFsQixFQUF3QixXQUF4QjtPQUF2QixDQUFyQixDQWpETTtBQWtETixXQUFLLE9BQUwsQ0FBYSxPQUFiLEVBQXNCLFVBQUMsS0FBRDtlQUFXLE9BQUssTUFBTCxDQUFZLE1BQVosQ0FBbUIsS0FBbkI7T0FBWCxDQUF0Qjs7O0FBbERNLFVBcUROLENBQUssSUFBTCxDQUFVLFlBQVYsQ0FBdUIsVUFBQyxHQUFELEVBQVM7QUFDOUIsWUFBSSxTQUFKLEdBQWdCLE1BQWhCLENBRDhCO0FBRTlCLFlBQUksUUFBSixDQUFhLENBQWIsRUFBZ0IsQ0FBaEIsRUFBbUIsSUFBSSxLQUFKLEVBQVcsSUFBSSxNQUFKLENBQTlCLENBRjhCO09BQVQsQ0FBdkI7OztBQXJETSxVQTJETixDQUFLLElBQUwsQ0FBVSxXQUFWLENBQXNCLEtBQUssUUFBTCxDQUF0Qjs7O0FBM0RNLFVBOEROLENBQUssS0FBTCxDQUFXLFlBQVgsR0FBMEIsS0FBSyxNQUFMLENBQVksT0FBWjs7O0FBOURwQixVQWlFRixLQUFLLFFBQUwsRUFBZTtBQUNqQixhQUFLLFdBQUwsR0FEaUI7QUFFakIsYUFBSyxTQUFMLEdBRmlCO09BQW5COzs7U0EvTWlCO0VBQXlCLFdBQVcsVUFBWDs7a0JBQXpCIiwiZmlsZSI6IlBsYXllckV4cGVyaWVuY2UuanMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgKiBhcyBzb3VuZHdvcmtzIGZyb20gJ3NvdW5kd29ya3MvY2xpZW50JztcbmltcG9ydCBTYW1wbGVTeW50aCBmcm9tICcuL1NhbXBsZVN5bnRoJztcbmltcG9ydCBMb29wZXIgZnJvbSAnLi9Mb29wZXInO1xuaW1wb3J0IENpcmNsZXMgZnJvbSAnLi9DaXJjbGVzJztcbmltcG9ydCBhdWRpb0ZpbGVzIGZyb20gJy4vYXVkaW9GaWxlcyc7XG5cbmNvbnN0IGNsaWVudCA9IHNvdW5kd29ya3MuY2xpZW50O1xuXG5jb25zdCB2aWV3VGVtcGxhdGUgPSBgXG4gIDxjYW52YXMgY2xhc3M9XCJiYWNrZ3JvdW5kXCI+PC9jYW52YXM+XG4gIDxkaXYgY2xhc3M9XCJmb3JlZ3JvdW5kXCI+XG4gICAgPGRpdiBjbGFzcz1cInNlY3Rpb24tdG9wIGZsZXgtbWlkZGxlXCI+PC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInNlY3Rpb24tY2VudGVyIGZsZXgtY2VudGVyXCI+XG4gICAgPCUgaWYgKHN0YXRlID09PSAncmVzZXQnKSB7ICU+XG4gICAgICA8cD5XYWl0aW5nIGZvcjxicj5ldmVyeWJvZHk8YnI+Z2V0dGluZyByZWFkeeKApjwvcD5cbiAgICA8JSB9IGVsc2UgaWYgKHN0YXRlID09PSAnZW5kJykgeyAlPlxuICAgICAgPHA+VGhhdCdzIGFsbC48YnI+VGhhbmtzITwvcD5cbiAgICA8JSB9IGVsc2UgeyAlPlxuICAgICAgPHA+XG4gICAgICA8JSBpZiAobnVtQXZhaWxhYmxlID4gMCkgeyAlPlxuICAgICAgICBZb3UgaGF2ZTxiciAvPlxuICAgICAgICA8JSBpZiAobnVtQXZhaWxhYmxlID09PSBtYXhEcm9wcykgeyAlPlxuICAgICAgICAgIDxzcGFuIGNsYXNzPVwiaHVnZVwiPjwlPSBudW1BdmFpbGFibGUgJT48L3NwYW4+XG4gICAgICAgIDwlIH0gZWxzZSB7ICU+XG4gICAgICAgICAgPHNwYW4gY2xhc3M9XCJodWdlXCI+PCU9IG51bUF2YWlsYWJsZSAlPiBvZiA8JT0gbWF4RHJvcHMgJT48L3NwYW4+XG4gICAgICAgIDwlIH0gJT5cbiAgICAgICAgPGJyIC8+PCU9IChudW1BdmFpbGFibGUgPT09IDEpID8gJ2Ryb3AnIDogJ2Ryb3BzJyAlPiB0byBwbGF5XG4gICAgICA8JSB9IGVsc2UgeyAlPlxuICAgICAgICA8c3BhbiBjbGFzcz1cImJpZ1wiPkxpc3RlbiE8L3NwYW4+XG4gICAgICA8JSB9ICU+XG4gICAgICA8L3A+XG4gICAgPCUgfSAlPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJzZWN0aW9uLWJvdHRvbSBmbGV4LW1pZGRsZVwiPjwvZGl2PlxuICA8L2Rpdj5cbmA7XG5cbmV4cG9ydCBkZWZhdWx0IGNsYXNzIFBsYXllckV4cGVyaWVuY2UgZXh0ZW5kcyBzb3VuZHdvcmtzLkV4cGVyaWVuY2Uge1xuICBjb25zdHJ1Y3RvcigpIHtcbiAgICBzdXBlcigpO1xuXG4gICAgLy8gY29uZmlndXJlIHJlcXVpcmVkIHNlcnZpY2VzXG4gICAgdGhpcy53ZWxjb21lID0gdGhpcy5yZXF1aXJlKCd3ZWxjb21lJyk7XG4gICAgdGhpcy5sb2FkZXIgPSB0aGlzLnJlcXVpcmUoJ2xvYWRlcicsIHsgZmlsZXM6IGF1ZGlvRmlsZXMgfSk7XG4gICAgdGhpcy5jaGVja2luID0gdGhpcy5yZXF1aXJlKCdjaGVja2luJyk7XG4gICAgdGhpcy5zeW5jID0gdGhpcy5yZXF1aXJlKCdzeW5jJyk7XG4gICAgdGhpcy5wYXJhbXMgPSB0aGlzLnJlcXVpcmUoJ3NoYXJlZC1wYXJhbXMnKTtcbiAgICB0aGlzLm1vdGlvbklucHV0ID0gdGhpcy5yZXF1aXJlKCdtb3Rpb24taW5wdXQnLCB7IGRlc2NyaXB0b3JzOiBbJ2FjY2VsZXJhdGlvbkluY2x1ZGluZ0dyYXZpdHknXSB9KTtcbiAgICB0aGlzLnNjaGVkdWxlciA9IHRoaXMucmVxdWlyZSgnc2NoZWR1bGVyJywgeyBsb29rYWhlYWQ6IDAuMDUwIH0pO1xuXG4gICAgLy8gcmVxdWlyZXMgbW9iaWxlIGRldmljZVxuICAgIHRoaXMucmVxdWlyZSgncGxhdGZvcm0nLCB7IGZlYXR1cmVzOiAnbW9iaWxlLWRldmljZScgfSk7XG5cbiAgICAvLyBhIHNpbXBsZSBzYW1wbGUgcGxheWVyIHdpdGggYSBsaXN0IG9mIHNhbXBsZXNcbiAgICB0aGlzLnN5bnRoID0gbmV3IFNhbXBsZVN5bnRoKCk7XG5cbiAgICAvLyBjb250cm9sIHBhcmFtZXRlcnNcbiAgICB0aGlzLnN0YXRlID0gJ3Jlc2V0JztcbiAgICB0aGlzLm1heERyb3BzID0gMDtcblxuICAgIHRoaXMubG9vcFBhcmFtcyA9IHt9O1xuICAgIHRoaXMubG9vcFBhcmFtcy5kaXYgPSAzO1xuICAgIHRoaXMubG9vcFBhcmFtcy5wZXJpb2QgPSA3LjU7XG4gICAgdGhpcy5sb29wUGFyYW1zLmF0dGVudWF0aW9uID0gMC43MDcxMDY3ODExODY1NTtcbiAgICB0aGlzLmxvb3BQYXJhbXMubWluR2FpbiA9IDAuMTtcblxuICAgIHRoaXMuYXV0b1BsYXkgPSAnb2ZmJzsgLy8gYXV0b21hdGljIChyYW5kb20pIHBsYXlpbmc6ICdkaXNhYmxlJywgJ29mZicsICdvbidcbiAgICB0aGlzLnF1YW50aXplID0gMDsgLy8gcXVhbnRpemF0aW9uIHN0ZXAgaW5cblxuICAgIC8vIHJlbmRlcmVyIGdlbmVyYXRpbmcgZ3Jvd2luZyBjaXJjbGVzIG9uIHRvdWNoXG4gICAgdGhpcy5yZW5kZXJlciA9IG5ldyBDaXJjbGVzKCk7XG5cbiAgICAvLyBlYWNoIHRvdWNoIHN0YXJ0cyBpdHMgb3duIGxvb3AgZ2VuZXJhdGVkIGJ5IHRoZSAnbG9vcGVyJ1xuICAgIHRoaXMubG9vcGVyID0gbmV3IExvb3Blcih0aGlzLnNjaGVkdWxlciwgdGhpcy5zeW50aCwgdGhpcy5yZW5kZXJlciwgdGhpcy5sb29wUGFyYW1zLCAoKSA9PiB0aGlzLnVwZGF0ZUNvdW50KCkpO1xuICB9XG5cbiAgaW5pdCgpIHtcbiAgICAvLyBzZXR1cCB2aWV3IChjcmVhdG9yLCB0ZW1wbGF0ZSBhbmQgY29udGVudClcbiAgICB0aGlzLnZpZXdDdG9yID0gc291bmR3b3Jrcy5DYW52YXNWaWV3O1xuICAgIHRoaXMudmlld1RlbXBsYXRlID0gdmlld1RlbXBsYXRlO1xuICAgIHRoaXMudmlld0NvbnRlbnQgPSB7XG4gICAgICBzdGF0ZTogdGhpcy5zdGF0ZSxcbiAgICAgIG1heERyb3A6IDAsXG4gICAgICBudW1BdmFpbGFibGU6IDAsXG4gICAgfVxuXG4gICAgLy8gY3JlYXRlIHZpZXcgd2l0aCB0aGUgY3JlYXRvciwgdGVtcGxhdGUgYW5kIGNvbnRlbnQgZ2l2ZW4gYWJvdmVcbiAgICB0aGlzLnZpZXcgPSB0aGlzLmNyZWF0ZVZpZXcoKTtcbiAgfVxuXG4gIHRyaWdnZXIoeCwgeSkge1xuICAgIGNvbnN0IHNvdW5kUGFyYW1zID0ge1xuICAgICAgaW5kZXg6IGNsaWVudC5pbmRleCxcbiAgICAgIGdhaW46IDEsXG4gICAgICB4OiB4LFxuICAgICAgeTogeSxcbiAgICB9O1xuXG4gICAgbGV0IHRpbWUgPSB0aGlzLnNjaGVkdWxlci5zeW5jVGltZTtcblxuICAgIC8vIHF1YW50aXplXG4gICAgLy8gaWYgKHRoaXMucXVhbnRpemUgPiAwKVxuICAgIC8vICAgc2VydmVyVGltZSA9IE1hdGguY2VpbCh0aW1lIC8gdGhpcy5xdWFudGl6ZSkgKiB0aGlzLnF1YW50aXplO1xuXG4gICAgdGhpcy5sb29wZXIuc3RhcnQodGltZSwgc291bmRQYXJhbXMsIHRydWUpO1xuICAgIHRoaXMuc2VuZCgnc291bmQnLCB0aW1lLCBzb3VuZFBhcmFtcyk7XG4gIH1cblxuICBjbGVhcigpIHtcbiAgICAvLyByZW1vdmUgYXQgb3duIGxvb3BlclxuICAgIHRoaXMubG9vcGVyLnJlbW92ZShjbGllbnQuaW5kZXgsIHRydWUpO1xuXG4gICAgLy8gcmVtb3ZlIGF0IG90aGVyIHBsYXllcnNcbiAgICB0aGlzLnNlbmQoJ2NsZWFyJyk7XG4gIH1cblxuICB1cGRhdGVDb3VudCgpIHtcbiAgICB0aGlzLnZpZXdDb250ZW50Lm1heERyb3BzID0gdGhpcy5tYXhEcm9wcztcbiAgICB0aGlzLnZpZXdDb250ZW50Lm1lc3NhZ2UgPSB1bmRlZmluZWQ7XG5cbiAgICBpZiAodGhpcy5zdGF0ZSA9PT0gJ3Jlc2V0Jykge1xuICAgICAgdGhpcy52aWV3Q29udGVudC5zdGF0ZSA9ICdyZXNldCc7XG4gICAgfSBlbHNlIGlmICh0aGlzLnN0YXRlID09PSAnZW5kJyAmJiB0aGlzLmxvb3Blci5sb29wcy5sZW5ndGggPT09IDApIHtcbiAgICAgIHRoaXMudmlld0NvbnRlbnQuc3RhdGUgPSAnZW5kJztcbiAgICB9IGVsc2Uge1xuICAgICAgdGhpcy52aWV3Q29udGVudC5zdGF0ZSA9IHRoaXMuc3RhdGU7XG4gICAgICB0aGlzLnZpZXdDb250ZW50Lm51bUF2YWlsYWJsZSA9IE1hdGgubWF4KDAsIHRoaXMubWF4RHJvcHMgLSB0aGlzLmxvb3Blci5udW1Mb2NhbExvb3BzKTtcbiAgICB9XG5cbiAgICB0aGlzLnZpZXcucmVuZGVyKCcuc2VjdGlvbi1jZW50ZXInKTtcbiAgfVxuXG4gIGF1dG9UcmlnZ2VyKCkge1xuICAgIGlmICh0aGlzLmF1dG9QbGF5ID09PSAnb24nKSB7XG4gICAgICBpZiAodGhpcy5zdGF0ZSA9PT0gJ3J1bm5pbmcnICYmIHRoaXMubG9vcGVyLm51bUxvY2FsTG9vcHMgPCB0aGlzLm1heERyb3BzKVxuICAgICAgICB0aGlzLnRyaWdnZXIoTWF0aC5yYW5kb20oKSwgTWF0aC5yYW5kb20oKSk7XG5cbiAgICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICB0aGlzLmF1dG9UcmlnZ2VyKCk7XG4gICAgICB9LCBNYXRoLnJhbmRvbSgpICogMjAwMCArIDUwKTtcbiAgICB9XG4gIH1cblxuICBhdXRvQ2xlYXIoKSB7XG4gICAgaWYgKHRoaXMuYXV0b1BsYXkgPT09ICdvbicpIHtcbiAgICAgIGlmICh0aGlzLmxvb3Blci5udW1Mb2NhbExvb3BzID4gMClcbiAgICAgICAgdGhpcy5jbGVhcihNYXRoLnJhbmRvbSgpLCBNYXRoLnJhbmRvbSgpKTtcblxuICAgICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIHRoaXMuYXV0b0NsZWFyKCk7XG4gICAgICB9LCBNYXRoLnJhbmRvbSgpICogNjAwMDAgKyA2MDAwMCk7XG4gICAgfVxuICB9XG5cbiAgc2V0U3RhdGUoc3RhdGUpIHtcbiAgICBpZiAoc3RhdGUgIT09IHRoaXMuc3RhdGUpIHtcbiAgICAgIHRoaXMuc3RhdGUgPSBzdGF0ZTtcbiAgICAgIHRoaXMudXBkYXRlQ291bnQoKTtcbiAgICB9XG4gIH1cblxuICBzZXRNYXhEcm9wcyhtYXhEcm9wcykge1xuICAgIGlmIChtYXhEcm9wcyAhPT0gdGhpcy5tYXhEcm9wcykge1xuICAgICAgdGhpcy5tYXhEcm9wcyA9IG1heERyb3BzO1xuICAgICAgdGhpcy51cGRhdGVDb3VudCgpO1xuICAgIH1cbiAgfVxuXG4gIHNldEF1dG9QbGF5KGF1dG9QbGF5KSB7XG4gICAgaWYgKHRoaXMuYXV0b1BsYXkgIT09ICdkaXNhYmxlJyAmJiBhdXRvUGxheSAhPT0gdGhpcy5hdXRvUGxheSkge1xuICAgICAgdGhpcy5hdXRvUGxheSA9IGF1dG9QbGF5O1xuXG4gICAgICBpZiAoYXV0b1BsYXkgPT09ICdvbicpIHtcbiAgICAgICAgdGhpcy5hdXRvVHJpZ2dlcigpO1xuICAgICAgICB0aGlzLmF1dG9DbGVhcigpO1xuICAgICAgfVxuICAgIH1cbiAgfVxuXG4gIHN0YXJ0KCkge1xuICAgIHN1cGVyLnN0YXJ0KCk7XG5cbiAgICAvLyBqdXN0IGluaXQgb25jZVxuICAgIGlmICghdGhpcy5oYXNTdGFydGVkKVxuICAgICAgdGhpcy5pbml0KCk7XG5cbiAgICAvLyBzaG93IHZpZXdcbiAgICB0aGlzLnNob3coKTtcblxuICAgIC8vIHNldHVwIHNoYXJlZCBwYXJhbWV0ZXIgKGNvbmR1Y3RvcikgbGlzdGVuZXJzXG4gICAgY29uc3QgcGFyYW1zID0gdGhpcy5wYXJhbXM7XG4gICAgcGFyYW1zLmFkZEl0ZW1MaXN0ZW5lcignc3RhdGUnLCAoc3RhdGUpID0+IHRoaXMuc2V0U3RhdGUoc3RhdGUpKTtcbiAgICBwYXJhbXMuYWRkSXRlbUxpc3RlbmVyKCdtYXhEcm9wcycsICh2YWx1ZSkgPT4gdGhpcy5zZXRNYXhEcm9wcyh2YWx1ZSkpO1xuICAgIHBhcmFtcy5hZGRJdGVtTGlzdGVuZXIoJ2xvb3BEaXYnLCAodmFsdWUpID0+IHRoaXMubG9vcFBhcmFtcy5kaXYgPSB2YWx1ZSk7XG4gICAgcGFyYW1zLmFkZEl0ZW1MaXN0ZW5lcignbG9vcFBlcmlvZCcsICh2YWx1ZSkgPT4gdGhpcy5sb29wUGFyYW1zLnBlcmlvZCA9IHZhbHVlKTtcbiAgICBwYXJhbXMuYWRkSXRlbUxpc3RlbmVyKCdsb29wQXR0ZW51YXRpb24nLCAodmFsdWUpID0+IHRoaXMubG9vcFBhcmFtcy5hdHRlbnVhdGlvbiA9IHZhbHVlKTtcbiAgICBwYXJhbXMuYWRkSXRlbUxpc3RlbmVyKCdtaW5HYWluJywgKHZhbHVlKSA9PiB0aGlzLmxvb3BQYXJhbXMubWluR2FpbiA9IHZhbHVlKTtcbiAgICBwYXJhbXMuYWRkSXRlbUxpc3RlbmVyKCdhdXRvUGxheScsICh2YWx1ZSkgPT4gdGhpcy5zZXRBdXRvUGxheSh2YWx1ZSkpO1xuICAgIHBhcmFtcy5hZGRJdGVtTGlzdGVuZXIoJ2NsZWFyJywgKCkgPT4gdGhpcy5sb29wZXIucmVtb3ZlQWxsKCkpO1xuXG4gICAgLy8gc2V0dXAgbW90aW9uIGlucHV0IGxpc3RlbmVyc1xuICAgIGlmICh0aGlzLm1vdGlvbklucHV0LmlzQXZhaWxhYmxlKCdhY2NlbGVyYXRpb25JbmNsdWRpbmdHcmF2aXR5JykpIHtcbiAgICAgIHRoaXMubW90aW9uSW5wdXQuYWRkTGlzdGVuZXIoJ2FjY2VsZXJhdGlvbkluY2x1ZGluZ0dyYXZpdHknLCAoZGF0YSkgPT4ge1xuICAgICAgICBjb25zdCBhY2NYID0gZGF0YVswXTtcbiAgICAgICAgY29uc3QgYWNjWSA9IGRhdGFbMV07XG4gICAgICAgIGNvbnN0IGFjY1ogPSBkYXRhWzJdO1xuICAgICAgICBjb25zdCBtYWcgPSBNYXRoLnNxcnQoYWNjWCAqIGFjY1ggKyBhY2NZICogYWNjWSArIGFjY1ogKiBhY2NaKTtcblxuICAgICAgICAvLyBjbGVhciBzY3JlZW4gb24gc2hha2luZ1xuICAgICAgICBpZiAobWFnID4gMjApIHtcbiAgICAgICAgICB0aGlzLmNsZWFyKCk7XG4gICAgICAgICAgdGhpcy5hdXRvUGxheSA9ICdkaXNhYmxlJzsgLy8gZGlzYWJsZSBhdXRvIHBsYXkgb24gc2hha2VcbiAgICAgICAgfVxuICAgICAgfSk7XG4gICAgfVxuXG4gICAgLy8gY3JlYXRlIHRvdWNoIGV2ZW50IHNvdXJjZSByZWZlcnJpbmcgdG8gb3VyIHZpZXdcbiAgICBjb25zdCBzdXJmYWNlID0gbmV3IHNvdW5kd29ya3MuVG91Y2hTdXJmYWNlKHRoaXMudmlldy4kZWwpO1xuXG4gICAgLy8gc2V0dXAgdG91Y2ggbGlzdGVuZXJzXG4gICAgc3VyZmFjZS5hZGRMaXN0ZW5lcigndG91Y2hzdGFydCcsIChpZCwgbm9ybVgsIG5vcm1ZKSA9PiB7XG4gICAgICBpZiAodGhpcy5zdGF0ZSA9PT0gJ3J1bm5pbmcnICYmIHRoaXMubG9vcGVyLm51bUxvY2FsTG9vcHMgPCB0aGlzLm1heERyb3BzKVxuICAgICAgICB0aGlzLnRyaWdnZXIobm9ybVgsIG5vcm1ZKTtcblxuICAgICAgdGhpcy5hdXRvUGxheSA9ICdkaXNhYmxlJzsgLy8gZGlzYWJsZSBhdXRvIHBsYXkgb24gdG91Y2hcbiAgICB9KTtcblxuICAgIC8vIHNldHVwIGxpc3RlbmVycyBmb3IgbWVzc2FnZXMgZnJvbSBzZXJ2ZXJcbiAgICB0aGlzLnJlY2VpdmUoJ2VjaG8nLCAodGltZSwgc291bmRQYXJhbXMpID0+IHRoaXMubG9vcGVyLnN0YXJ0KHRpbWUsIHNvdW5kUGFyYW1zKSk7XG4gICAgdGhpcy5yZWNlaXZlKCdjbGVhcicsIChpbmRleCkgPT4gdGhpcy5sb29wZXIucmVtb3ZlKGluZGV4KSk7XG5cbiAgICAvLyByZWRlcmVyIHN0YXJ0cyB3aXRoIGJsYWNrIHNjcmVlblxuICAgIHRoaXMudmlldy5zZXRQcmVSZW5kZXIoKGN0eCkgPT4ge1xuICAgICAgY3R4LmZpbGxTdHlsZSA9ICcjMDAwJztcbiAgICAgIGN0eC5maWxsUmVjdCgwLCAwLCBjdHgud2lkdGgsIGN0eC5oZWlnaHQpO1xuICAgIH0pO1xuXG4gICAgLy8gYWRkIHJlbmRlcmVyIHRvIHZpZXdcbiAgICB0aGlzLnZpZXcuYWRkUmVuZGVyZXIodGhpcy5yZW5kZXJlcik7XG5cbiAgICAvLyBzZXQgc3ludGggYXVkaW8gYnVmZmVyc1xuICAgIHRoaXMuc3ludGguYXVkaW9CdWZmZXJzID0gdGhpcy5sb2FkZXIuYnVmZmVycztcblxuICAgIC8vIGxhdW5jaCBhdXRvcGxheSAoZm9yIHRlc3RpbmcpXG4gICAgaWYgKHRoaXMuYXV0b1BsYXkpIHtcbiAgICAgIHRoaXMuYXV0b1RyaWdnZXIoKTtcbiAgICAgIHRoaXMuYXV0b0NsZWFyKCk7XG4gICAgfVxuICB9XG59XG4iXX0=